=== nikol4o0o/XML/XML/Smartwatches.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT smartwatchCatalog (smartwatch+)>
        <!ELEMENT smartwatch (id,brand, model, year, gallery, price, colourWatch, storage, RAM,  body, features, connection, band )>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT gallery (frontImage, sideImage, onHandImage)>
        <!ELEMENT frontImage (#PCDATA)>
        <!ELEMENT sideImage (#PCDATA)>
        <!ELEMENT onHandImage (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT colourWatch (#PCDATA)>
        <!ELEMENT storage (#PCDATA)>
        <!ELEMENT RAM (#PCDATA)>
        <!ELEMENT body (display, shape, weight, caseMaterial)>
        <!ELEMENT display (size, type, resolution, isLTPO)>
        <!ELEMENT size (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT resolution (#PCDATA)>
        <!ELEMENT isLTPO (#PCDATA)>
        <!ELEMENT shape (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT caseMaterial (#PCDATA)>

        <!ELEMENT features (battery, CPU, OS)>
        <!ELEMENT battery (capacity, hoursRated, typeOfBattery)>
        <!ELEMENT capacity (#PCDATA)>
        <!ELEMENT hoursRated (#PCDATA)>
        <!ELEMENT typeOfBattery (#PCDATA)>
        <!ELEMENT CPU (#PCDATA)>
        <!ELEMENT OS (#PCDATA) >

        <!ELEMENT connection (WLAN, bluetooth, payment, NFC)>
        <!ELEMENT WLAN (#PCDATA)>
        <!ELEMENT bluetooth (#PCDATA)>
        <!ELEMENT payment (#PCDATA)>
        <!ELEMENT NFC (#PCDATA) >

        <!ELEMENT band (sizing, materialBand, colour, style) >
        <!ELEMENT sizing (#PCDATA)>
        <!ELEMENT materialBand (#PCDATA)>
        <!ELEMENT colour (#PCDATA)>
        <!ELEMENT style (#PCDATA)>

        <!ATTLIST body waterRating CDATA #REQUIRED>
        <!ATTLIST model number CDATA #REQUIRED>
        <!ATTLIST price currency (Лева|Евро) "Лева">
        <!ATTLIST OS version CDATA #REQUIRED>
        <!ATTLIST features ECG  (Да|Не) "Не">
        <!ATTLIST features BloodO2 (Да|Не) "Не">
        <!ATTLIST band changeable (Да|Не) "Не">
        <!ATTLIST OS compatibility CDATA #REQUIRED>
        <!ATTLIST display alwaysON  (Да|Не) "Да">

=== nikol4o0o/XML/XML/valid_xml_4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE smartwatchCatalog SYSTEM "Smartwatches.dtd">

<smartwatchCatalog>
    <smartwatch>
        <id>0006</id>
        <brand>Шиаоми</brand>
        <model number="M2108W1">Смарт часовник ЕС1</model>
        <year>2021</year>
        <gallery>
            <frontImage>Images/frontImageS1.jpeg</frontImage>
            <sideImage>Images/sideImageS1.jpeg</sideImage>
            <onHandImage>Images/onHandS1.jpeg</onHandImage>
        </gallery>
        <price currency="Евро">150</price>
        <colourWatch>Сребрист </colourWatch>
        <storage>16ГБ</storage>
        <RAM>1.5ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Да">
                <size>46мм</size>
                <type>AMOLED</type>
                <resolution>466x466</resolution>
                <isLTPO>Не</isLTPO>
            </display>
            <shape>Кръгъл</shape>
            <weight>41 грама</weight>
            <caseMaterial>Неръждаема стомана</caseMaterial>
        </body>
        <features ECG="Не" BloodO2="Да">
            <battery>
                <capacity>470 мАч</capacity>
                <hoursRated>288 часа</hoursRated>
                <typeOfBattery>Литиево-полимерна</typeOfBattery>
            </battery>
            <CPU>Snapdragon </CPU>
            <OS compatibility="iOS и Android устройства" version="3">WearOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n/ac</WLAN>
            <bluetooth>5.2</bluetooth>
            <payment>Гугъл Стандарт за безконтактно мобилно плащане</payment>
            <NFC>Да</NFC>
        </connection>
        <band changeable="Да">
            <sizing>Регулируема</sizing>
            <materialBand>Кожена</materialBand>
            <colour>Кафява</colour>
            <style>Елегантна</style>
        </band>
    </smartwatch>
</smartwatchCatalog>

=== nikol4o0o/XML/XML/valid_xml_3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE smartwatchCatalog SYSTEM "Smartwatches.dtd">

<smartwatchCatalog>
    <smartwatch>
        <id>0005</id>
        <brand>Епъл</brand>
        <model number="А2356">Серия СЕ</model>
        <year>2020</year>
        <gallery>
            <frontImage>Images/frontImageSE.jpeg</frontImage>
            <sideImage>Images/sideImageSE.jpeg</sideImage>
            <onHandImage>Images/onHandSE.jpeg</onHandImage>
        </gallery>
        <price currency="Лева">629</price>
        <colourWatch>Златен </colourWatch>
        <storage>32ГБ</storage>
        <RAM>1ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Не">
                <size>44мм</size>
                <type>OLED</type>
                <resolution>448x368</resolution>
                <isLTPO>Не</isLTPO>
            </display>
            <shape>Правоъгълен</shape>
            <weight>36.4 грама</weight>
            <caseMaterial>Алуминий серия 7000</caseMaterial>
        </body>
        <features ECG="Не" BloodO2="Не">
            <battery>
                <capacity>303.8 мАч</capacity>
                <hoursRated>18 часа</hoursRated>
                <typeOfBattery>Литиево-йонна</typeOfBattery>
            </battery>
            <CPU>Apple S5</CPU>
            <OS compatibility="iOS устройства" version="8.3">WatchOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n/ac</WLAN>
            <bluetooth>5.0</bluetooth>
            <payment>Епъл Стандарт за безконтактно мобилно плащане</payment>
            <NFC>Да</NFC>
        </connection>
        <band changeable="Да">
            <sizing>S/M и M/L каишки</sizing>
            <materialBand>Силиконова</materialBand>
            <colour>Розова</colour>
            <style>Спортна</style>
        </band>
    </smartwatch>
    </smartwatchCatalog>

=== nikol4o0o/XML/XML/valid_xml_5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE smartwatchCatalog SYSTEM "Smartwatches.dtd">
<smartwatchCatalog>
    <smartwatch>
        <id>0007</id>
        <brand>Уан Плюс</brand>
        <model number="W301GB">Часновник</model>
        <year>2021</year>
        <gallery>
            <frontImage>Images/frontImageOnePlus.jpeg</frontImage>
            <sideImage>Images/sideImageOnePlus.jpeg</sideImage>
            <onHandImage>Images/onHandOnePlus.jpeg</onHandImage>
        </gallery>
        <price currency="Лева">310</price>
        <colourWatch>Среднощно черно </colourWatch>
        <storage>4ГБ</storage>
        <RAM>1ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Да">
                <size>44мм</size>
                <type>AMOLED</type>
                <resolution>454x454</resolution>
                <isLTPO>Не</isLTPO>
            </display>
            <shape>Кръгъл</shape>
            <weight>45 грама</weight>
            <caseMaterial>Алуминив корпус, пластмасов гръб</caseMaterial>
        </body>
        <features ECG="Не" BloodO2="Да">
            <battery>
                <capacity>402 мАч</capacity>
                <hoursRated>168 часа</hoursRated>
                <typeOfBattery>Литиево-йонна</typeOfBattery>
            </battery>
            <CPU>Snapdragon</CPU>
            <OS compatibility="iOS и Android устройства" version="1">OnePlus Watch OS</OS>
        </features>
        <connection>
            <WLAN>802.11 b/g/n</WLAN>
            <bluetooth>5.0</bluetooth>
            <payment>Не поддържа</payment>
            <NFC>Не</NFC>
        </connection>
        <band changeable="Да">
            <sizing>Регулируема</sizing>
            <materialBand>Силиконова</materialBand>
            <colour>Черно</colour>
            <style>Спортна</style>
        </band>
    </smartwatch>
</smartwatchCatalog>

=== nikol4o0o/XML/XML/valid_xml_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/xml" href="txt_transformation_1.xsl" version="1.0"?>-->
<!--<?xml-stylesheet type="text/xml" href="txt_transformation_2.xsl" version="1.0"?>-->
<!--<?xml-stylesheet type="text/xml" href="HTML_transformation_2.xsl" version="1.0"?>-->
<!--<?xml-stylesheet type="text/xml" href="HTML_transformation_3.xsl" version="1.0"?>-->
<!--<?xml-stylesheet type="text/xml" href="HTML_transformation_4.xsl" version="1.0"?>-->
<!--<?xml-stylesheet type="text/xml" href="XML_transformation_1.xsl" version="1.0"?>-->
<!--<?xml-stylesheet type="text/xml" href="XML_transformation_2.xsl" version="1.0"?>-->
<?xml-stylesheet type="text/xml" href="XML_transformation_1.xsl" version="1.0"?>


<!DOCTYPE smartwatchCatalog SYSTEM "Smartwatches.dtd">
<smartwatchCatalog>
    <smartwatch>
        <id>0001</id>
        <brand>Епъл </brand>
        <model number="A2292">Уоч Серия 6</model>
        <year>2020</year>
        <gallery>
            <frontImage>Images/frontImageS6.jpeg</frontImage>
            <sideImage>Images/sideImageS6.jpeg</sideImage>
            <onHandImage>Images/onHandS6.jpeg</onHandImage>
        </gallery>
        <price currency="Лева">899</price>
        <colourWatch>Черен </colourWatch>
        <storage>32ГБ</storage>
        <RAM>1ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Да">
                <size>44мм</size>
                <type>OLED</type>
                <resolution>448x368</resolution>
                <isLTPO>Да</isLTPO>
            </display>
            <shape>Правоъгълен</shape>
            <weight>36.5 грама</weight>
            <caseMaterial>Алуминий серия 7000</caseMaterial>
        </body>
        <features ECG="Да" BloodO2="Да">
            <battery>
                <capacity>303.8 мАч</capacity>
                <hoursRated>18 часа</hoursRated>
                <typeOfBattery>Литиево-йонна</typeOfBattery>
            </battery>
            <CPU>Apple S6</CPU>
            <OS compatibility="iOS устройства" version="8.3">WatchOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n/ac</WLAN>
            <bluetooth>5.0</bluetooth>
            <payment>Епъл Стандарт за безконтактно мобилно плащане</payment>
            <NFC>Да</NFC>
        </connection>
        <band changeable="Да">
            <sizing>S/M и M/L каишки</sizing>
            <materialBand>Силиконова</materialBand>
            <colour>Черен</colour>
            <style>Спортна</style>
        </band>
    </smartwatch>

    <smartwatch>
        <id>0002</id>
        <brand>Самсунг</brand>
        <model number="SM-R870">Галакси Уоч 4</model>
        <year>2021</year>
        <gallery>
            <frontImage>Images/frontImageG4.jpeg</frontImage>
            <sideImage>Images/sideImageG4.jpeg</sideImage>
            <onHandImage>Images/onHandG4.jpeg</onHandImage>
        </gallery>
        <price currency="Лева">450</price>
        <colourWatch>Сребрист </colourWatch>
        <storage>16ГБ</storage>
        <RAM>1.5ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Да">
                <size>44мм</size>
                <type>AMOLED</type>
                <resolution>450x450</resolution>
                <isLTPO>Не</isLTPO>
            </display>
            <shape>Кръгъл</shape>
            <weight>30.3 грама</weight>
            <caseMaterial>Алуминий</caseMaterial>
        </body>
        <features ECG="Да" BloodO2="Да">
            <battery>
                <capacity>361 мАч</capacity>
                <hoursRated>20 часа</hoursRated>
                <typeOfBattery>Литиево-йонна</typeOfBattery>
            </battery>
            <CPU>Exynos W920</CPU>
            <OS compatibility="Android устройства" version="3">WearOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n</WLAN>
            <bluetooth>5.0</bluetooth>
            <payment>Самсунг Стандарт за безконтактно мобилно плащане</payment>
            <NFC>Да</NFC>
        </connection>
        <band changeable="Да">
            <sizing>Универсален размер</sizing>
            <materialBand>Силиконова</materialBand>
            <colour>Бял</colour>
            <style>Спортна</style>
        </band>
    </smartwatch>

    <smartwatch>
        <id>0003</id>
        <brand>Епъл </brand>
        <model number="А2475"> Уоч Серия 7</model>
        <year>2021</year>
        <gallery>
            <frontImage>Images/frontImageS7.jpeg</frontImage>
            <sideImage>Images/sideImageS7.jpeg</sideImage>
            <onHandImage>Images/onHandS7.jpeg</onHandImage>
        </gallery>
        <price currency="Евро">750</price>
        <colourWatch>Златен </colourWatch>
        <storage>32ГБ</storage>
        <RAM>1ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Да">
                <size>41мм</size>
                <type>OLED</type>
                <resolution>484x396</resolution>
                <isLTPO>Да</isLTPO>
            </display>
            <shape>Правоъгълен</shape>
            <weight>42.3 грама</weight>
            <caseMaterial>Титан</caseMaterial>
        </body>
        <features ECG="Да" BloodO2="Да">
            <battery>
                <capacity>309 мАч</capacity>
                <hoursRated>18 часа</hoursRated>
                <typeOfBattery>Литиево-йонна</typeOfBattery>
            </battery>
            <CPU>Apple S7</CPU>
            <OS compatibility="iOS устройства" version ="8.3">WatchOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n/ac</WLAN>
            <bluetooth>5.0</bluetooth>
            <payment>Apple Pay Стандарт за безконтактно мобилно плащане</payment>
            <NFC>Да</NFC>
        </connection>
        <band changeable="Да">
            <sizing>Универсална, магнитно премиум закопчаване</sizing>
            <materialBand>Кожена</materialBand>
            <colour>Кафяв</colour>
            <style>Премиум, елегантна</style>
        </band>
    </smartwatch>
</smartwatchCatalog>

=== nikol4o0o/XML/XML/valid_xml_2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE smartwatchCatalog SYSTEM "Smartwatches.dtd">
<smartwatchCatalog>
    <smartwatch>
        <id>0004</id>
        <brand>Huawei</brand>
        <model number="MIL-B19">Watch GT3</model>
        <year>2021</year>
        <gallery>
            <frontImage>Images/frontImageGT3.jpeg</frontImage>
            <sideImage>Images/sideImageGT3.jpeg</sideImage>
            <onHandImage>Images/onHandGt3.jpeg</onHandImage>
        </gallery>
        <price currency="Евро">210</price>
        <colourWatch>Сребрист </colourWatch>
        <storage>16ГБ</storage>
        <RAM>4ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Не">
                <size>46мм</size>
                <type>AMOLED</type>
                <resolution>466x466</resolution>
                <isLTPO>Не</isLTPO>
            </display>
            <shape>Кръгъл</shape>
            <weight>42.6 грама</weight>
            <caseMaterial>Неръждаема стомана, пластмасов гръб</caseMaterial>
        </body>
        <features ECG="Не" BloodO2="Да">
            <battery>
                <capacity>455 мАч</capacity>
                <hoursRated>168 часа</hoursRated>
                <typeOfBattery>Литиево-полимерна</typeOfBattery>
            </battery>
            <CPU>Kirin 9090</CPU>
            <OS compatibility="iOS и Android устройства" version="2">HarmonyOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n/ac</WLAN>
            <bluetooth>5.1</bluetooth>
            <payment>Не поддържа безконтактно мобилно плащане</payment>
            <NFC>Не</NFC>
        </connection>
        <band changeable="Да">
            <sizing>Универсална регулируема</sizing>
            <materialBand>Неръждаема стомана</materialBand>
            <colour>Сребрист</colour>
            <style>Елегантна</style>
        </band>
    </smartwatch>
    </smartwatchCatalog>

=== nikol4o0o/XML/XML/validateProba.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE smartwatchCatalog SYSTEM "Smartwatches.dtd">
<?xml-stylesheet type="text/xml" href="HTML_transformation_3.xsl" version="1.0"?>

<smartwatchCatalog>
    <smartwatch>
        <id>0008</id>
        <brand>Samsung</brand>
        <model number="SM-R890">Галакси Уоч4 Класик</model>
        <year>2021</year>
        <gallery>
            <frontImage>Images/frontImageS4Classic.jpeg</frontImage>
            <sideImage>Images/sideImageS4Classic.jpeg</sideImage>
            <onHandImage>Images/onHandS4Classic.jpeg</onHandImage>
        </gallery>
        <price currency="Евро">1000</price>
        <colourWatch>Черен</colourWatch>
        <storage>16ГБ</storage>
        <RAM>1.5ГБ</RAM>
        <body waterRating="50 метра">
            <display alwaysON="Да">
                <size>46мм</size>
                <type>AMOLED</type>
                <resolution>450X450</resolution>
                <isLTPO>Не</isLTPO>
            </display>
            <shape>Кръгла</shape>
            <weight>52 грама</weight>
            <caseMaterial>Неръждаема стомана</caseMaterial>
        </body>
        <features ECG="Да" BloodO2="Да">
            <battery>
                <capacity>361 мАч</capacity>
                <hoursRated>24 часа</hoursRated>
                <typeOfBattery>Литиево-йонна</typeOfBattery>
            </battery>
            <CPU>Exynos W920 </CPU>
            <OS compatibility="Android устройства" version="3">WearOS</OS>
        </features>
        <connection>
            <WLAN>802.11 a/b/g/n</WLAN>
            <bluetooth>5.0</bluetooth>
            <payment>Samsung Pay Стандарт за безконтактно мобилно плащане</payment>
            <NFC>Да</NFC>
        </connection>
        <band changeable="Да">
            <sizing>Универсален размер</sizing>
            <materialBand>Силиконова</materialBand>
            <colour>Черен</colour>
            <style>Елегантна</style>
        </band>
    </smartwatch>
</smartwatchCatalog>
